/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package formularios;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author keyle
 */
public class MDIprincipal extends javax.swing.JFrame {

    frmCategorias fCategorias = null;
    frmClientes fClientes = null;
    frmArticulos fArticulos = null; 
    frmFacturacion fFacturacion = null;
    frmConsultaFactura fCosultas = null;
    
    
    public MDIprincipal() {
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Super Mercado Del Chino");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        String ImagenFondo = "" ;
        int Segundo = (int) (System.currentTimeMillis() % 10 );
        if ( Segundo <= 3 )
        { ImagenFondo = "/Imagenes/SuperMercado_a.jpg" ; }
        else if ( Segundo <= 6 )
        { ImagenFondo = "/Imagenes/SuperMercado_b.jpg" ; }
        else 
        { ImagenFondo = "/Imagenes/SuperMercado_c.jpg" ; }

        ImageIcon icon = new ImageIcon(getClass().getResource(ImagenFondo));
        Image img = icon.getImage();
        Escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g)
            {
                g.drawImage(img,0,0,getWidth(),getHeight(),this);
            }
        }
        ;
        menuBar = new javax.swing.JMenuBar();
        mnProcesos = new javax.swing.JMenu();
        mnFacturacion = new javax.swing.JMenuItem();
        mnuConsultar = new javax.swing.JMenu();
        mnConsultar = new javax.swing.JMenuItem();
        mnCatalogos = new javax.swing.JMenu();
        mnCategorias = new javax.swing.JMenuItem();
        mnArticulos = new javax.swing.JMenuItem();
        mnClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnProcesos.setMnemonic('f');
        mnProcesos.setText("Procesos");

        mnFacturacion.setMnemonic('o');
        mnFacturacion.setText("facturacion");
        mnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFacturacionActionPerformed(evt);
            }
        });
        mnProcesos.add(mnFacturacion);

        menuBar.add(mnProcesos);

        mnuConsultar.setMnemonic('e');
        mnuConsultar.setText("Consultas");

        mnConsultar.setMnemonic('t');
        mnConsultar.setText("consultar facturas");
        mnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultarActionPerformed(evt);
            }
        });
        mnuConsultar.add(mnConsultar);

        menuBar.add(mnuConsultar);

        mnCatalogos.setMnemonic('h');
        mnCatalogos.setText("Catalogos");

        mnCategorias.setMnemonic('c');
        mnCategorias.setText("categorias");
        mnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCategoriasActionPerformed(evt);
            }
        });
        mnCatalogos.add(mnCategorias);

        mnArticulos.setMnemonic('a');
        mnArticulos.setText("articulos");
        mnArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArticulosActionPerformed(evt);
            }
        });
        mnCatalogos.add(mnArticulos);

        mnClientes.setText("clientes");
        mnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClientesActionPerformed(evt);
            }
        });
        mnCatalogos.add(mnClientes);

        menuBar.add(mnCatalogos);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCategoriasActionPerformed
        if (fCategorias==null || fCategorias.isClosed())
        { 
        fCategorias = new frmCategorias();
        Escritorio.add(fCategorias);
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = fCategorias.getSize();
        fCategorias.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);

        }
        
        
        fCategorias.toFront();
        fCategorias.setVisible(true);
    }//GEN-LAST:event_mnCategoriasActionPerformed

    private void mnArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArticulosActionPerformed
        if (fArticulos==null || fArticulos.isClosed())
        {
        fArticulos = new frmArticulos();
        Escritorio.add(fArticulos);
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = fArticulos.getSize();
        fArticulos.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        }
        fArticulos.toFront();
        fArticulos.setVisible(true);
    }//GEN-LAST:event_mnArticulosActionPerformed

    private void mnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClientesActionPerformed
        if (fClientes==null || fClientes.isClosed())
        {
        fClientes = new frmClientes();
        Escritorio.add(fClientes);
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = fClientes.getSize();
        fClientes.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        }
        fClientes.toFront();
        fClientes.setVisible(true);
    }//GEN-LAST:event_mnClientesActionPerformed

    private void mnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFacturacionActionPerformed
        if (fFacturacion==null || fFacturacion.isClosed())
        {
        fFacturacion = new frmFacturacion();
        Escritorio.add(fFacturacion);
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = fFacturacion.getSize();
        fFacturacion.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        }
        fFacturacion.toFront();
        fFacturacion.setVisible(true);
    }//GEN-LAST:event_mnFacturacionActionPerformed

    private void mnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarActionPerformed
        if (fCosultas==null || fCosultas.isClosed())
        {
        fCosultas = new frmConsultaFactura();
        Escritorio.add(fCosultas);
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = fCosultas.getSize();
        fCosultas.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        }
        fCosultas.toFront();
        fCosultas.setVisible(true);
    }//GEN-LAST:event_mnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnArticulos;
    private javax.swing.JMenu mnCatalogos;
    private javax.swing.JMenuItem mnCategorias;
    private javax.swing.JMenuItem mnClientes;
    private javax.swing.JMenuItem mnConsultar;
    private javax.swing.JMenuItem mnFacturacion;
    private javax.swing.JMenu mnProcesos;
    private javax.swing.JMenu mnuConsultar;
    // End of variables declaration//GEN-END:variables

}
